// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/modot/internal/modfile/sourceprovider/github"
	_ "github.com/lewtec/modot/internal/modfile/sourceprovider/local"
)
