package codebase

// this file is generated by internal/devtools/autoregistry, do not edit manually
import (
	pkg_config "github.com/lucasew/workspaced/cmd/workspaced/codebase/config"
)

type Command struct {
	Config   *pkg_config.Command
	Apply    *Apply
	Plan     *Plan
	Lint     *Lint
	Format   *Format
	Lsp      *Lsp
	CIStatus *CIStatus `cmd:"ci-status"`
}
