// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/modot/internal/driver/screen/sway"
	_ "github.com/lewtec/modot/internal/driver/screen/x11"
)
