// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/modot/internal/driver/audio/prelude"
	_ "github.com/lewtec/modot/internal/driver/battery/prelude"
	_ "github.com/lewtec/modot/internal/driver/brightness/prelude"
	_ "github.com/lewtec/modot/internal/driver/camera/prelude"
	_ "github.com/lewtec/modot/internal/driver/clipboard/prelude"
	_ "github.com/lewtec/modot/internal/driver/dialog/prelude"
	_ "github.com/lewtec/modot/internal/driver/env/prelude"
	_ "github.com/lewtec/modot/internal/driver/exec/prelude"
	_ "github.com/lewtec/modot/internal/driver/fetchurl/prelude"
	_ "github.com/lewtec/modot/internal/driver/httpclient/prelude"
	_ "github.com/lewtec/modot/internal/driver/media/prelude"
	_ "github.com/lewtec/modot/internal/driver/notification/prelude"
	_ "github.com/lewtec/modot/internal/driver/opener/prelude"
	_ "github.com/lewtec/modot/internal/driver/power/prelude"
	_ "github.com/lewtec/modot/internal/driver/rsync/prelude"
	_ "github.com/lewtec/modot/internal/driver/screen/prelude"
	_ "github.com/lewtec/modot/internal/driver/screenshot/prelude"
	_ "github.com/lewtec/modot/internal/driver/shell/prelude"
	_ "github.com/lewtec/modot/internal/driver/shim/prelude"
	_ "github.com/lewtec/modot/internal/driver/svgraster/prelude"
	_ "github.com/lewtec/modot/internal/driver/terminal/prelude"
	_ "github.com/lewtec/modot/internal/driver/tray/prelude"
	_ "github.com/lewtec/modot/internal/driver/wallpaper/prelude"
	_ "github.com/lewtec/modot/internal/driver/wm/prelude"
)
