// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/modot/internal/palette/genetic"
	_ "github.com/lewtec/modot/internal/palette/materialyou"
)
