// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/modot/internal/module/provider/core"
	_ "github.com/lewtec/modot/internal/module/provider/local"
)
