package home

// this file is generated by internal/devtools/autoregistry, do not edit manually
import (
	pkg_apply "github.com/lewtec/modot/cmd/modot/home/apply"
	pkg_backup "github.com/lewtec/modot/cmd/modot/home/backup"
	pkg_config "github.com/lewtec/modot/cmd/modot/home/config"
	pkg_plan "github.com/lewtec/modot/cmd/modot/home/plan"
	pkg_sync "github.com/lewtec/modot/cmd/modot/home/sync"
)

type Command struct {
	Apply  *pkg_apply.Command
	Backup *pkg_backup.Command
	Config *pkg_config.Command
	Plan   *pkg_plan.Command
	Sync   *pkg_sync.Command
}
