// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/modot/internal/driver/clipboard/lew"
	_ "github.com/lewtec/modot/internal/driver/clipboard/termux"
)
