// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/modot/internal/driver/clipboard/termux"
	_ "github.com/lewtec/modot/internal/driver/clipboard/wlcopy"
	_ "github.com/lewtec/modot/internal/driver/clipboard/xclip"
)
