// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/modot/internal/driver/opener/lew"
	_ "github.com/lewtec/modot/internal/driver/opener/termux"
)
