// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/modot/internal/driver/notification/fromkit"
	_ "github.com/lewtec/modot/internal/driver/notification/termux"
)
