package palette

// this file is generated by internal/devtools/autoregistry, do not edit manually
import (
	pkg_drivers "github.com/lucasew/workspaced/cmd/workspaced/utils/palette/drivers"
	pkg_generate "github.com/lucasew/workspaced/cmd/workspaced/utils/palette/generate"
)

type Command struct {
	Drivers *pkg_drivers.Command
	Generate *pkg_generate.Command
}
