// Code generated by lewkit generate prelude. DO NOT EDIT.

package prelude

import (
	_ "github.com/lewtec/modot/internal/driver/terminal/alacritty"
	_ "github.com/lewtec/modot/internal/driver/terminal/foot"
	_ "github.com/lewtec/modot/internal/driver/terminal/kitty"
	_ "github.com/lewtec/modot/internal/driver/terminal/termux"
)
